// SPDX-License-Identifier: MIT
// Copyright: 2023 Econolite Systems, Inc.
namespace Econolite.Ode.Auditing
{
    public static class SupportedAuditEventTypes
    {
        public static readonly string ConfigurationGroup = "ConfigurationGroup";
        public static readonly string KeycloakAdminGroup = "KeycloakAdminGroup";
        public static readonly string KeycloakUserGroup = "KeycloakUserGroup";

        public static readonly Dictionary<AuditEventType, AuditEventTypeModel> AuditEventTypes = new Dictionary<AuditEventType, AuditEventTypeModel>
        {
            // Configuration Events
            { AuditEventType.ActionSet, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Action Set", Event = "ActionSet" } },
            { AuditEventType.ConnectedVehicle, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Connected Vehicle", Event = "ConnectedVehicle" } },
            { AuditEventType.DeviceManagerConfiguration, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Device Manager Configuration", Event = "DeviceManagerConfiguration" } },
            { AuditEventType.DeviceManagerChannel, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Device Manager Channel", Event = "DeviceManagerChannel" } },
            { AuditEventType.Entity, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Entity", Event = "Entity" } },
            { AuditEventType.EntityType, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Entity Type", Event = "EntityType" } },
            { AuditEventType.EnvironmentalSensorsStations, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Environmental Sensors Stations", Event = "EnvironmentalSensorsStations" } },
            { AuditEventType.LogicStatement, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Logic Statement", Event = "LogicStatement" } },
            { AuditEventType.PavementConditionConfiguration, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Pavement Condition Configuration", Event = "PavementConditionConfiguration" } },
            { AuditEventType.PavementConditionStatus, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Pavement Condition Status", Event = "PavementConditionStatus" } },
            { AuditEventType.RoadsideUnit, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Roadside Unit", Event = "RoadsideUnit" } },
            { AuditEventType.Signal, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Signal", Event = "Signal" } },
            { AuditEventType.SystemModeller, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "System Modeller", Event = "SystemModeller" } },
            { AuditEventType.WrongWayDriver, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Wrong Way Driver", Event = "WrongWayDriver" } },
            { AuditEventType.WeatherResponsive, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Weather Responsive", Event = "WeatherResponsive" } },
            { AuditEventType.TravelerInformationMessages, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Traveler Information Messages", Event = "TravelerInformationMessages" } },
            { AuditEventType.VehiclePriority, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Vehicle Priority", Event = "VehiclePriority" } },
            { AuditEventType.AcyclicaConfiguration, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Acyclica Configuration", Event = "AcyclicaConfiguration" } },
            { AuditEventType.TwilioConfiguration, new AuditEventTypeModel { Group = ConfigurationGroup, Name = "Twilio Configuration", Event = "TwilioConfiguration" } },

            // Keycloak Admin Events
            { AuditEventType.KeycloakAdminCreate, new AuditEventTypeModel { Group = KeycloakAdminGroup, Name = "Admin Create", Event = "CREATE" } },
            { AuditEventType.KeycloakAdminUpdate, new AuditEventTypeModel { Group = KeycloakAdminGroup, Name = "Admin Update", Event = "UPDATE" } },
            { AuditEventType.KeycloakAdminDelete, new AuditEventTypeModel { Group = KeycloakAdminGroup, Name = "Admin Delete", Event = "DELETE" } },
            { AuditEventType.KeycloakAdminAction, new AuditEventTypeModel { Group = KeycloakAdminGroup, Name = "Admin Action", Event = "ACTION" } },

            // Keycloak User Events
            { AuditEventType.KeycloakUserLogin, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Login", Event = "LOGIN" } },
            { AuditEventType.KeycloakUserLoginError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Login Error", Event = "LOGIN_ERROR" } },
            { AuditEventType.KeycloakUserRegister, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Register", Event = "REGISTER" } },
            { AuditEventType.KeycloakUserRegisterError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Register Error", Event = "REGISTER_ERROR" } },
            { AuditEventType.KeycloakUserLogout, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Logout", Event = "LOGOUT" } },
            { AuditEventType.KeycloakUserLogoutError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Logout Error", Event = "LOGOUT_ERROR" } },
            { AuditEventType.KeycloakUserCodeToToken, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Code To Token", Event = "CODE_TO_TOKEN" } },
            { AuditEventType.KeycloakUserCodeToTokenError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Code To Token Error", Event = "CODE_TO_TOKEN_ERROR" } },
            { AuditEventType.KeycloakUserClientLogin, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Login", Event = "CLIENT_LOGIN" } },
            { AuditEventType.KeycloakUserClientLoginError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Login Error", Event = "CLIENT_LOGIN_ERROR" } },
            { AuditEventType.KeycloakUserRefreshToken, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Refresh Token", Event = "REFRESH_TOKEN" } },
            { AuditEventType.KeycloakUserRefreshTokenError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Refresh Token Error", Event = "REFRESH_TOKEN_ERROR" } },
            { AuditEventType.KeycloakUserIntrospectToken, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Introspect Token", Event = "INTROSPECT_TOKEN" } },
            { AuditEventType.KeycloakUserIntrospectTokenError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Introspect Token Error", Event = "INTROSPECT_TOKEN_ERROR" } },
            { AuditEventType.KeycloakUserFederatedIdentityLink, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Federated Identity Link", Event = "FEDERATED_IDENTITY_LINK" } },
            { AuditEventType.KeycloakUserFederatedIdentityLinkError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Federated Identity Link Error", Event = "FEDERATED_IDENTITY_LINK_ERROR" } },
            { AuditEventType.KeycloakUserRemoveFederatedIdentity, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Remove Federated Identity", Event = "REMOVE_FEDERATED_IDENTITY" } },
            { AuditEventType.KeycloakUserRemoveFederatedIdentityError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Remove Federated Identity Error", Event = "REMOVE_FEDERATED_IDENTITY_ERROR" } },
            { AuditEventType.KeycloakUserUpdateEmail, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Email", Event = "UPDATE_EMAIL" } },
            { AuditEventType.KeycloakUserUpdateEmailError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Email Error", Event = "UPDATE_EMAIL_ERROR" } },
            { AuditEventType.KeycloakUserUpdateProfile, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Profile", Event = "UPDATE_PROFILE" } },
            { AuditEventType.KeycloakUserUpdateProfileError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Profile Error", Event = "UPDATE_PROFILE_ERROR" } },
            { AuditEventType.KeycloakUserUpdatePassword, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Password", Event = "UPDATE_PASSWORD" } },
            { AuditEventType.KeycloakUserUpdatePasswordError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Password Error", Event = "UPDATE_PASSWORD_ERROR" } },
            { AuditEventType.KeycloakUserUpdateTotp, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Totp", Event = "UPDATE_TOTP" } },
            { AuditEventType.KeycloakUserUpdateTotpError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Totp Error", Event = "UPDATE_TOTP_ERROR" } },
            { AuditEventType.KeycloakUserVerifyEmail, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Verify Email", Event = "VERIFY_EMAIL" } },
            { AuditEventType.KeycloakUserVerifyEmailError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Verify Email Error", Event = "VERIFY_EMAIL_ERROR" } },
            { AuditEventType.KeycloakUserVerifyProfile, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Verify Profile", Event = "VERIFY_PROFILE" } },
            { AuditEventType.KeycloakUserVerifyProfileError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Verify Profile Error", Event = "VERIFY_PROFILE_ERROR" } },
            { AuditEventType.KeycloakUserRemoveTotp, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Remove Totp", Event = "REMOVE_TOTP" } },
            { AuditEventType.KeycloakUserRemoveTotpError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Remove Totp Error", Event = "REMOVE_TOTP_ERROR" } },
            { AuditEventType.KeycloakUserGrantConsent, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Grant Consent", Event = "GRANT_CONSENT" } },
            { AuditEventType.KeycloakUserGrantConsentError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Grant Consent Error", Event = "GRANT_CONSENT_ERROR" } },
            { AuditEventType.KeycloakUserUpdateConsent, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Consent", Event = "UPDATE_CONSENT" } },
            { AuditEventType.KeycloakUserUpdateConsentError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Update Consent Error", Event = "UPDATE_CONSENT_ERROR" } },
            { AuditEventType.KeycloakUserRevokeGrant, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Revoke Grant", Event = "REVOKE_GRANT" } },
            { AuditEventType.KeycloakUserRevokeGrantError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Revoke Grant Error", Event = "REVOKE_GRANT_ERROR" } },
            { AuditEventType.KeycloakUserSendVerifyEmail, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Send Verify Email", Event = "SEND_VERIFY_EMAIL" } },
            { AuditEventType.KeycloakUserSendVerifyEmailError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Send Verify Email Error", Event = "SEND_VERIFY_EMAIL_ERROR" } },
            { AuditEventType.KeycloakUserSendResetPassword, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Send Reset Password", Event = "SEND_RESET_PASSWORD" } },
            { AuditEventType.KeycloakUserSendResetPasswordError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Send Reset Password Error", Event = "SEND_RESET_PASSWORD_ERROR" } },
            { AuditEventType.KeycloakUserSendIdentityProviderLink, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Send Identity Provider Link", Event = "SEND_IDENTITY_PROVIDER_LINK" } },
            { AuditEventType.KeycloakUserSendIdentityProviderLinkError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Send Identity Provider Link Error", Event = "SEND_IDENTITY_PROVIDER_LINK_ERROR" } },
            { AuditEventType.KeycloakUserResetPassword, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Reset Password", Event = "RESET_PASSWORD" } },
            { AuditEventType.KeycloakUserResetPasswordError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Reset Password Error", Event = "RESET_PASSWORD_ERROR" } },
            { AuditEventType.KeycloakUserRestartAuthentication, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Restart Authentication", Event = "RESTART_AUTHENTICATION" } },
            { AuditEventType.KeycloakUserRestartAuthenticationError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Restart Authentication Error", Event = "RESTART_AUTHENTICATION_ERROR" } },
            { AuditEventType.KeycloakUserInvalidSignature, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Invalid Signature", Event = "INVALID_SIGNATURE" } },
            { AuditEventType.KeycloakUserInvalidSignatureError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Invalid Signature Error", Event = "INVALID_SIGNATURE_ERROR" } },
            { AuditEventType.KeycloakUserRegisterNode, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Register Node", Event = "REGISTER_NODE" } },
            { AuditEventType.KeycloakUserRegisterNodeError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Register Node Error", Event = "REGISTER_NODE_ERROR" } },
            { AuditEventType.KeycloakUserUnregisterNode, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Unregister Node", Event = "UNREGISTER_NODE" } },
            { AuditEventType.KeycloakUserUnregisterNodeError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Unregister Node Error", Event = "UNREGISTER_NODE_ERROR" } },
            { AuditEventType.KeycloakUserUserInfoRequest, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User User Information Request", Event = "USER_INFO_REQUEST" } },
            { AuditEventType.KeycloakUserUserInfoRequestError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User User Information Request Error", Event = "USER_INFO_REQUEST_ERROR" } },
            { AuditEventType.KeycloakUserIdentityProviderLinkAccount, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Link Account", Event = "IDENTITY_PROVIDER_LINK_ACCOUNT" } },
            { AuditEventType.KeycloakUserIdentityProviderLinkAccountError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Link Account Error", Event = "IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR" } },
            { AuditEventType.KeycloakUserIdentityProviderLogin, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Login", Event = "IDENTITY_PROVIDER_LOGIN" } },
            { AuditEventType.KeycloakUserIdentityProviderLoginError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Login Error", Event = "IDENTITY_PROVIDER_LOGIN_ERROR" } },
            { AuditEventType.KeycloakUserIdentityProviderFirstLogin, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider First Login", Event = "IDENTITY_PROVIDER_FIRST_LOGIN" } },
            { AuditEventType.KeycloakUserIdentityProviderFirstLoginError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider First Login Error", Event = "IDENTITY_PROVIDER_FIRST_LOGIN_ERROR" } },
            { AuditEventType.KeycloakUserIdentityProviderPostLogin, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Post Login", Event = "IDENTITY_PROVIDER_POST_LOGIN" } },
            { AuditEventType.KeycloakUserIdentityProviderPostLoginError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Post Login Error", Event = "IDENTITY_PROVIDER_POST_LOGIN_ERROR" } },
            { AuditEventType.KeycloakUserIdentityProviderResponse, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Response", Event = "IDENTITY_PROVIDER_RESPONSE" } },
            { AuditEventType.KeycloakUserIdentityProviderResponseError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Response Error", Event = "IDENTITY_PROVIDER_RESPONSE_ERROR" } },
            { AuditEventType.KeycloakUserIdentityProviderRetrieveToken, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Retrieve Token", Event = "IDENTITY_PROVIDER_RETRIEVE_TOKEN" } },
            { AuditEventType.KeycloakUserIdentityProviderRetrieveTokenError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Identity Provider Retrieve Token Error", Event = "IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR" } },
            { AuditEventType.KeycloakUserImpersonate, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Impersonate", Event = "IMPERSONATE" } },
            { AuditEventType.KeycloakUserImpersonateError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Impersonate Error", Event = "IMPERSONATE_ERROR" } },
            { AuditEventType.KeycloakUserCustomRequiredAction, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Custom Required Action", Event = "CUSTOM_REQUIRED_ACTION" } },
            { AuditEventType.KeycloakUserCustomRequiredActionError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Custom Required Action Error", Event = "CUSTOM_REQUIRED_ACTION_ERROR" } },
            { AuditEventType.KeycloakUserExecuteActions, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Execute Actions", Event = "EXECUTE_ACTIONS" } },
            { AuditEventType.KeycloakUserExecuteActionsError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Execute Actions Error", Event = "EXECUTE_ACTIONS_ERROR" } },
            { AuditEventType.KeycloakUserExecuteActionToken, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Execute Action Token", Event = "EXECUTE_ACTION_TOKEN" } },
            { AuditEventType.KeycloakUserExecuteActionTokenError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Execute Action Token Error", Event = "EXECUTE_ACTION_TOKEN_ERROR" } },
            { AuditEventType.KeycloakUserClientInfo, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Information", Event = "CLIENT_INFO" } },
            { AuditEventType.KeycloakUserClientInfoError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Information Error", Event = "CLIENT_INFO_ERROR" } },
            { AuditEventType.KeycloakUserClientRegister, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Register", Event = "CLIENT_REGISTER" } },
            { AuditEventType.KeycloakUserClientRegisterError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Register Error", Event = "CLIENT_REGISTER_ERROR" } },
            { AuditEventType.KeycloakUserClientUpdate, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Update", Event = "CLIENT_UPDATE" } },
            { AuditEventType.KeycloakUserClientUpdateError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Update Error", Event = "CLIENT_UPDATE_ERROR" } },
            { AuditEventType.KeycloakUserClientDelete, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Delete", Event = "CLIENT_DELETE" } },
            { AuditEventType.KeycloakUserClientDeleteError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Delete Error", Event = "CLIENT_DELETE_ERROR" } },
            { AuditEventType.KeycloakUserClientInitiatedAccountLinking, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Initiated Account Linking", Event = "CLIENT_INITIATED_ACCOUNT_LINKING" } },
            { AuditEventType.KeycloakUserClientInitiatedAccountLinkingError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Client Initiated Account Linking Error", Event = "CLIENT_INITIATED_ACCOUNT_LINKING_ERROR" } },
            { AuditEventType.KeycloakUserTokenExchange, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Token Exchange", Event = "TOKEN_EXCHANGE" } },
            { AuditEventType.KeycloakUserTokenExchangeError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Token Exchange Error", Event = "TOKEN_EXCHANGE_ERROR" } },
            { AuditEventType.KeycloakUserOAuth2DeviceAuth, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User OAuth2 Device Authorizaiton", Event = "OAUTH2_DEVICE_AUTH" } },
            { AuditEventType.KeycloakUserOAuth2DeviceAuthError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User OAuth2 Device Authorization Error", Event = "OAUTH2_DEVICE_AUTH_ERROR" } },
            { AuditEventType.KeycloakUserOAuth2DeviceVerifyUserCode, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User OAuth2 Device Verify User Code", Event = "OAUTH2_DEVICE_VERIFY_USER_CODE" } },
            { AuditEventType.KeycloakUserOAuth2DeviceVerifyUserCodeError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User OAuth2 Device Verify User Code Error", Event = "OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR" } },
            { AuditEventType.KeycloakUserOAuth2DeviceCodeToToken, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User OAuth2 Device Code To Token", Event = "OAUTH2_DEVICE_CODE_TO_TOKEN" } },
            { AuditEventType.KeycloakUserOAuth2DeviceCodeToTokenError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User OAuth2 Device Code To Token Error", Event = "OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR" } },
            { AuditEventType.KeycloakUserAuthReqIdToToken, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Authorization Request Id To Token", Event = "AUTHREQID_TO_TOKEN" } },
            { AuditEventType.KeycloakUserAuthReqIdToTokenError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Authorization Request Id To Token Error", Event = "AUTHREQID_TO_TOKEN_ERROR" } },
            { AuditEventType.KeycloakUserPermissionToken, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Permission Token", Event = "PERMISSION_TOKEN" } },
            { AuditEventType.KeycloakUserPermissionTokenError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Permission Token Error", Event = "PERMISSION_TOKEN_ERROR" } },
            { AuditEventType.KeycloakUserDeleteAccount, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Delete Account", Event = "DELETE_ACCOUNT" } },
            { AuditEventType.KeycloakUserDeleteAccountError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Delete Account Error", Event = "DELETE_ACCOUNT_ERROR" } },
            { AuditEventType.KeycloakUserPushedAuthorizationRequest, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Pushed Authorization Request", Event = "PUSHED_AUTHORIZATION_REQUEST" } },
            { AuditEventType.KeycloakUserPushedAuthorizationRequestError, new AuditEventTypeModel { Group = KeycloakUserGroup, Name = "User Pushed Authorization Request Error", Event = "PUSHED_AUTHORIZATION_REQUEST_ERROR" } },
        };
    }
}
